name: Keep Legal Tech Alive

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Legal Tech Platform
        run: |
          curl -s https://otaibi-law-q395.vercel.app/
          echo "Ping sent successfully to the Legal Tech link!"
